on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  cockpitKeyboard:
    runs-on: ubuntu-latest
    name: cockpit
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache qmk toolchain
        uses: actions/cache@v2
        env:
          cache-name: qmk-toolchain
        with:
          path: |
            /home/runner/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies for qmk build
        uses: mstksg/get-package@v1
        with:
          apt-get: git python3-pip dfu-util dfu-programmer avrdude 
      - name: Install qmk using pip
        working-directory: ./qmk_firmware
        run: |
          python3 -m pip install --user qmk
          qmk setup --yes --home .
      - name: Prepare qmk_firmware folder
        run: cp -R cockpit/ qmk_firmware/keyboards/
      - name: Build cockpit-keyboard-pcb firmware
        working-directory: ./qmk_firmware
        run: qmk compile -kb cockpit -km default 
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: cockpit-keyboard-pcb
          path: qmk_firmware/cockpit_default.hex